### ISSUE TITLE
Missing subtitles... (and new directory-structure)

### ISSUE THREAD

**Issue by bokoppe** [kvolden/nrk_download#2]
There seems to be some problems with the subtitles... 
Although the program reports downloading subtitles, the srt-files are empty.

This **may** be related to NRK's overhaul of their URL-structure/directory-structure - for example:

> https://tv.nrk.no/serie/tunnelen/sesong/3/episode/4

...for episode 4 in season 3 of the TV-series "Tunnelen".

**Comment by kvolden** [comment]
Are you using version 1.1.5? I am seeing an error during the saving of subtitles when I try to download your example, which seems to be different from what you are seeing. Do you have other examples which give no errors but empty srt-files?

EDIT: Nevermind, after fixing the first error, I now get an empty srt-file as well.

**Comment by kvolden** [comment]
This should be fixed now in v1.1.6, so I'm closing this issue. Thanks for reporting it, and feel free to reopen if the problem somehow persists, or create a new issue if you find other problems. :)
