### ISSUE TITLE
Veldig lange filnavn - tar med beskrivelse i tillegg til tittel

### ISSUE THREAD

**Issue by koppe** [kvolden/nrk_download#3]
I den senere tid har jeg lagt merke til at en del tv-programmer har faatt veldig lange filnavn - noen ganger lange nok til aa kraesje programmet - fordi beskrivelsen blir en del av filnavnet sammen med tittelen.  

Vet ikke hvorfor det skjer, men kanskje NRK har lagt om malene sine eller bruker en annen linjeskift-konvensjon eller noe...  Fra det tredje eksempelet (som kraesjer programmet) saa jeg det var ett \r\n linjeskift etter tittel og aarstall, saa det burde vaere mulig aa bryte filnavnet der (skjoent enda tidligere ville vaert bedre).

For slike tilfeller, kunne det uansett vaert flott med en opsjon (f.eks -o ) for aa spesifisere filnavnet manuelt...

Takk for ett flott program, og ha ett riktig Godt Nyttaar!

Tre eksempler, det siste krasjer programmet grunnet lengden:

   * https://tv.nrk.no/program/KOID25002019 
   * https://tv.nrk.no/program/KOID22001220 

   * https://tv.nrk.no/program/FDRI42000895

+++

Downloading 1 of 3:
Found Elvis: Aloha fra Hawaii Da Elvis sa aloha fra Hawaii så hele verden på. Konserten, den første som ble sendt via satelitt, er et must for alle Elvis-fans. Og egentlig alle andre.
Saving Elvis_ Aloha fra Hawaii Da Elvis sa aloha fra Hawaii så hele verden på. Konserten, den første som ble sendt via satelitt, er et must for alle Elvis-fans. Og egentlig alle andre..srt
Saving Elvis_ Aloha fra Hawaii Da Elvis sa aloha fra Hawaii så hele verden på. Konserten, den første som ble sendt via satelitt, er et must for alle Elvis-fans. Og egentlig alle andre..ts
(...)

Downloading 3 of 3:
Found Reisen til julestjernen Norsk spillefilm fra 1976. 
Den lille prinsesse Gulltopp forsvinner på selveste julenatten. Hun har gått ut i skogen helt alene for å finne julestjernen, som hun ønsker seg av hele sitt hjerte. 
Med Hanne Krogh, Knut Risan, Bente Børsum, Ingrid Larsen, Alf Nordvang og Anne Marit Jacobsen. 
Regi: Ola Solum. 
(5 år)
Saving Reisen til julestjernen Norsk spillefilm fra 1976. 
Den lille prinsesse Gulltopp forsvinner på selveste julenatten. Hun har gått ut i skogen helt alene for å finne julestjernen, som hun ønsker seg av hele sitt hjerte. 
Med Hanne Krogh, Knut Risan, Bente Børsum, Ingrid Larsen, Alf Nordvang og Anne Marit Jacobsen. 
Regi_ Ola Solum. 
(5 år).srt
Traceback (most recent call last):
  File "./nrk_download.py", line 203, in <module>
    main(programs)
  File "./nrk_download.py", line 189, in main
    download(program_id)
  File "./nrk_download.py", line 111, in download
    save_stream(meta)
  File "./nrk_download.py", line 80, in save_stream
    save_subtitles(meta['subtitles'], u'{}.srt'.format(filename_base))
  File "./nrk_download.py", line 61, in save_subtitles
    with io.open(filename, 'w') as f:
OSError: [Errno 36] File name too long: 'Reisen til julestjernen Norsk spillefilm fra 1976. \r\nDen lille prinsesse Gulltopp forsvinner på selveste julenatten. Hun har gått ut i skogen helt alene for å finne julestjernen, som hun ønsker seg av hele sitt hjerte. \r\nMed Hanne Krogh, Knut Risan, Bente Børsum, Ingrid Larsen, Alf Nordvang og Anne Marit Jacobsen. \r\nRegi_ Ola Solum. \r\n(5 år).srt'

**Comment by kvolden** [comment]
Jeg har sjekket programmene du linker til, og problemet er at NRK i enkelte tilfeller har lagt inn programbeskrivelsen også som undertittel i videoens metadata. Om det er en feil eller om det er meningen vet jeg ikke, men det må håndteres uansett, så jeg skal få lagt inn en eller annen sjekk som sørger for at den ikke lager ulovlig lange filnavn.

**Comment by kvolden** [comment]
Versjon 1.1.9 inneholder en fiks som dropper undertittelfeltet når det er identisk med feltet for programbeskrivelse. Har også lagt til en opsjon, -o/--output, for å spesifisere filnavn, slik du foreslo. Det virker som dette fikser problemet, så jeg lukker issuet nå. Bare opprett nye issues dersom det er noe mer som ikke virker. :)
